
---
include:
  - board: nice_nano_v2
    shield: sofle_dongle sofle_dongle_ssd1306 dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_ANSI_displayV2
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DUSE_INTERNATIONAL_LAYOUT
  - board: nice_nano_v2
    shield: sofle_dongle sofle_dongle_sh1106 dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_ANSI_displayV1
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DUSE_INTERNATIONAL_LAYOUT
  - board: nice_nano_v2
    shield: sofle_dongle sofle_dongle_ssd1306 dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_ABNT2_displayV2
  - board: nice_nano_v2
    shield: sofle_dongle sofle_dongle_sh1106 dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_ABNT2_displayV1
  - board: nice_nano_v2
    shield: sofle_left
    artifact-name: sofle_esquerdo
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: sofle_right
    artifact-name: sofle_direito
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset-firmware
